version: '3'

services:
  discord-bot:
    build: .
    container_name: dwarf-discord-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env.secret:/app/.env.secret
      - llm_cache:/tmp/discord_bot_llm_cache
    environment:
      - TZ=Asia/Seoul
      - PYTHONUNBUFFERED=1
    # 로그를 표준 출력으로 보내 Docker 로그에서 볼 수 있도록 합니다
    tty: true
    stdin_open: true

volumes:
  llm_cache:
    driver: local 