version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dwarf-discord-bot
    restart: unless-stopped
    env_file:
      - .env.secret
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./bot.log:/app/bot.log
    # 컨테이너가 중지될 때 깔끔하게 종료되도록 설정
    stop_signal: SIGINT
    # 기본 타임아웃 보다 긴 시간 설정 (초 단위)
    stop_grace_period: 30s 